apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bloodapp-to-db
spec:
  podSelector:
    matchLabels:
      app: bloodapp-db

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bloodapp
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 3306

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: bloodapp
      ports:
        - protocol: TCP
          port: 3306

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
